// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kytxajawylqnghbrqgjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dHhhamF3eWxxbmdoYnJxZ2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTM5MDIsImV4cCI6MjA2MTE4OTkwMn0.QZxkyWJC17aNabgHwkslju0y9skNBZ5dzOOPY_MfNEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);